// createApp = require('./app.js');
// database = require('./database.js');
// const app = createApp(database); // setup for database mocking
// const port = 5000;

const mysql = require('mysql2');
const express = require('express');
const session = require('express-session');
const cors = require('cors');
const path = require('path');
const port = 5000;
//const loginData = require('./data/db.json')

const fs = require('fs');
const e = require('cors');
const { builtinModules } = require('module');
//let filedata = fs.readFileSync('./data/db.json');
//let userData = JSON.parse(filedata);

const connection = mysql.createConnection({ 
	host     : 'localhost',
	user     : 'root',
	password : 'admin',
	database : 'nodelogin',
    multipleStatements: true
});

const app = express();
app.use(cors());
//app.use(cors({credentials: true, origin: 'http://localhost:3000'}));
app.use(session({
	secret: 'secret',
	saveUninitialized: false,
    resave: false,
    cookie: {secure: false}
}));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, 'static')));

//the above setup by Eric

app.get('/', function(request, response) {//ignore for now
	//response.sendFile(path.join(__dirname + '/login'));
    response.status(200).send("TEST");
});

// app.get('/', function (request, response) {
//     response.sendFile(path.join(_dirname, '/index'), function(err) {
//         if (err) {
//             response.status(500).send(err)
//         }  
//     })
// })

app.get("/loginstatus", (request, response) => { //done by Paul
    let username = request.session.username;
    let login = false;
    if (username != null) {
        login = true;
    }
    response.send([username,login]);
});

app.post('/auth', function(request, response) { //authenticating user logins //done by Eric
    //response.setHeader('Access-Control-Allow-Credentials', 'true')
    //console.log(request.body);

	// Capture the input fields
	let username = request.body.username;
	let password = request.body.password;
    let login;
    let SID;

	// Ensure the input fields exists and are not empty
	if (username && password) {
        console.log("Successfully obtained username and password");
		//Execute SQL query that'll select the account from the database based on the specified username and the password generated by the SHA2-256 hash function
		connection.query(`SELECT * FROM UserCredentials WHERE username = '${username}' AND password = SHA2('${password}', 256)`, function(error, results, fields) {
			// If there is an issue with the query, output the error
			if (error) throw error;
			// If the account exists
            if (request.session.loggedin == true) {
                console.log("You are already logged in! (BACKEND)");
                return response.send({
                    status: 'You are already logged in! (FROM BACKEND)',
                });
            }
			if (results.length > 0) {
				// Authenticate the user
                //loggedin = true;
				request.session.loggedin = true;
				request.session.username = username;
                login = request.session.loggedin;
                SID = request.sessionID;
                //request.session.save()
                response.send({
                    status: 'Successfully logged in. (FROM BACKEND)',
                    login,
                    username
                    //SID
                });
                console.log("Successfully logged in.");
                console.log(`Welcome back, ${request.session.username}!`);
                //console.log(request.sessionID)
                response.end();
                //response.status(200).end('OK');
                //response.redirect('http://localhost:3000/profile');
                //response.writeHead(301, {Location: `http://localhost:3000/profile`}).end();
			} 
            else {
				response.send({
                    status: 'Incorrect Username and/or Password! (FROM BACKEND)',
                });
				console.log("Incorrect Username and/or Password! (BACKEND)");
			}			
			response.end();
		});
	} else {
		response.send({
            status: 'Please enter Username and Password! (FROM BACKEND)'
        });
        console.log("Please enter Username and Password! (BACKEND)");
		response.end();
	}
});

app.listen(port, () => {console.log(`Server started on port ${port}`)});